site_name: actfts package

nav:
  - Home: index.md
  - Get started: Get_Started.md
  - References: References.md

theme:
  name: readthedocs
  logo: https://i.ibb.co/NxmBNBf/Logo-R-ACTFTS.png
  favicon: https://i.ibb.co/jRzQz7G/favicon.png